### ISSUE TITLE
How this plugin detects VPN connections?

### ISSUE THREAD

**Issue by musialny** [SomewhatSane/VPNShield-EXILED-Edition#3]

**Comment by SomewhatSane** [comment]
Hi,

Thank you for your interest in my plugin. VPNShield uses the IPHub ([https://iphub.info](https://iphub.info)) API in order to detect VPN connections. I am thinking about changing this sometime in the future to another API but I haven't had the time to get around to it yet, nor am I fully certain on what I want to do.

As this isn't an issue, I am going to close this however if you have any other questions or queries then please let me know.

Many thanks
